[package]
name = "gb-io"
version = "0.1.0"
build = "build.rs"

[build-dependencies]
string_cache_codegen = "0.4.2"

[dependencies]
itertools = "0.8"
circular = "0.2"
failure = "0.1.5"
string_cache = "0.7.3"
log = "0.4"
nom = "4.2.1"
serde = { version = "1.0", optional = true, features = ["derive"] }
bio = "0.25.0"


[dev-dependencies]
glob = "0.2.11"
bencher = "0.1.5"

[[bench]]
name = "parse"
harness = false
