[package]
edition = "2018"
name = "gb-io"
version = "0.5.0"
license = "MIT"
authors = ["David Leslie"]
homepage = "https://github.com/dlesl/gb-io"
repository = "https://github.com/dlesl/gb-io"
description = "A library for parsing, writing and manipulating Genbank sequence files"
build = "build.rs"
exclude = ["tests/*"]

[build-dependencies]
string_cache_codegen = "0.4.2"

[dependencies]
itertools = "0.8"
circular = "0.2"
err-derive = "0.1"
string_cache = "0.7.3"
log = "0.4"
nom = "4.2.3"
serde = { version = "1.0", optional = true, features = ["derive"] }
bio = "0.25.0"


[dev-dependencies]
glob = "0.3.0"
bencher = "0.1.5"
env_logger = "0.6.1"

[[bench]]
name = "parse"
harness = false
