name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Disable autocrlf on windows
      run: git config --global core.autocrlf false
    - uses: actions/checkout@v2
    - name: Lint
      run: cargo clippy -- -D warnings
    - name: Test
      run: cargo test
